version: "3"
services:
  api:
    environment:
      - NODE_ENV=production
    restart: always

  worker:
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - /var/lib/bootlegger/secrets:/app/secrets

  faktory:
    volumes:
      - /var/lib/faktory:/var/lib/faktory
    restart: always
